[build]
  functions = "functions/"
  publish = ""

[[plugins]]
  package = "netlify-plugin-form-submissions2"

  [plugins.inputs]
    formNames = "sampleApprovedComments"
    dataDirectory = "comment/_data"
